# Generated by Django 3.2.5 on 2021-08-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='url',
        ),
        migrations.AddField(
            model_name='password',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
