# Generated by Django 3.2.5 on 2021-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_auto_20210802_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='password',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
