# Generated by Django 3.2.5 on 2021-08-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0003_auto_20210804_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
