# Generated by Django 3.2.5 on 2021-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_alter_password_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
