# Generated by Django 3.2.5 on 2021-08-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0005_password_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='favorite',
            new_name='is_favorite',
        ),
    ]
