# Generated by Django 3.2.5 on 2021-08-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0006_rename_favorite_password_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
